Categories:
  - Graphics

License: MIT

AuthorName: Nathabee
WebSite: https://nathabee.github.io/beemage/demo/
SourceCode: https://github.com/nathabee/beemage
IssueTracker: https://github.com/nathabee/beemage/issues

RepoType: git
Repo: https://github.com/nathabee/beemage.git

Builds:
  - versionName: "0.2.5"
    versionCode: 1002005
    commit: v0.2.5

    # Android project is in a subdir of the repo.
    subdir: apps/android-native

    # Build the web bundle that is wrapped by android-native.
    build:
      - ../android-web/scripts/build-android-web.sh

    # Then run the Gradle build in the Android subdir.
    gradle:
      - yes

AutoUpdateMode: Version %v
UpdateCheckMode: Tags
CurrentVersion: "0.2.5"
CurrentVersionCode: 1002005
