#!/usr/bin/env bash
# scripts/prepare-release-commit.sh
set -euo pipefail

die()  { echo "ERROR: $*" >&2; exit 1; }
info() { echo "$*"; }
need() { command -v "$1" >/dev/null 2>&1 || die "Missing command: $1"; }

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

need git
need python3

[[ -f VERSION ]] || die "VERSION file missing"
ver="$(tr -d ' \t\r\n' < VERSION)"
[[ -n "$ver" ]] || die "VERSION is empty"
tag="v${ver}"

ANDROID_DIR="$ROOT_DIR/apps/android-native"
CHECK="$ANDROID_DIR/scripts/check.sh"
ENSURE_CHANGELOG="$ANDROID_DIR/scripts/ensure-fdroid-changelog.sh"

# New: tracked helper template (NOT .fdroid.yml)
FROID_TEMPLATE="$ANDROID_DIR/scripts/fdroid-template.yml"

[[ -x "$CHECK" ]] || die "Missing or not executable: $CHECK"
[[ -x "$ENSURE_CHANGELOG" ]] || die "Missing or not executable: $ENSURE_CHANGELOG"
[[ -f "$FROID_TEMPLATE" ]] || die "fdroid template not found: $FROID_TEMPLATE"

# If tag exists locally, never try to "prepare" (would require retagging).
if git rev-parse "$tag" >/dev/null 2>&1; then
  HEAD_SHA="$(git rev-parse HEAD)"
  TAG_SHA="$(git rev-parse "$tag")"
  [[ "$TAG_SHA" == "$HEAD_SHA" ]] || die "Tag $tag exists but does not point to HEAD.
Tag:  $TAG_SHA
HEAD: $HEAD_SHA
Refusing to prepare release commit. Fix by checking out the tagged commit or deleting/recreating the tag intentionally."
  info "OK: tag $tag already exists and points to HEAD; skipping prepare step."
  exit 0
fi

VC="$("$CHECK" --print-expected-versioncode)"
[[ -n "${VC:-}" ]] || die "Could not compute versionCode via: $CHECK --print-expected-versioncode"

CHANGELOG_PATH="apps/android-native/fastlane/metadata/android/en-US/changelogs/${VC}.txt"

dirty_count="$(git status --porcelain | wc -l | tr -d ' ')"
last_subject="$(git log -1 --pretty=%s 2>/dev/null || true)"

msg_ok="no"
if [[ "$last_subject" =~ ^v${ver}[[:space:]](—|-)[[:space:]]Epic: ]]; then
  msg_ok="yes"
fi

changelog_ok="no"
if [[ -f "$CHANGELOG_PATH" ]]; then
  changelog_ok="yes"
fi

# Only run when: dirty OR message mismatch OR changelog missing.
if [[ "$dirty_count" == "0" && "$msg_ok" == "yes" && "$changelog_ok" == "yes" ]]; then
  info "Release commit already prepared:"
  info "- working tree clean"
  info "- last commit message matches v${ver} — Epic:"
  info "- changelog exists: $CHANGELOG_PATH"
  exit 0
fi

info "== Prepare release commit =="
info "Version:     $ver"
info "Tag:         $tag"
info "versionCode: $VC"
info

# Guard (prepare-step): refuse generated output paths.
# We WANT your real source/docs/metadata changes to be committable here.
forbidden="$(
  git status --porcelain |
    awk '{
      p=$2;

      # generated docs publish outputs (committed later by release-all step 6)
      if (p ~ /^docs\/demo(\/|$)/) print p;
      else if (p == "docs/index.html") print p;
      else if (p ~ /^docs\/assets\/opencv(\/|$)/) print p;
      else if (p ~ /^docs\/assets\/pipelines(\/|$)/) print p;

      # release artifacts
      else if (p ~ /^(release)(\/|$)/) print p;

      # app build byproducts
      else if (p ~ /^apps\/[^\/]+\/dist(\/|$)/) print p;

      # android-web copied bundle into wrapper assets (generated by build step)
      else if (p ~ /^apps\/android-native\/app\/src\/main\/assets(\/|$)/) print p;

      # never commit local fdroidserver file if it exists
      else if (p == ".fdroid.yml") print p;
    }'
)"
[[ -z "$forbidden" ]] || {
  echo "Generated / forbidden outputs detected (do not include these in the release commit):"
  echo "$forbidden"
  die "Clean these (git restore / git clean) and rerun."
}

# Ask for epic text (commit subject)
default_epic=""
if [[ "$last_subject" =~ Epic:\ (.*)$ ]]; then
  default_epic="${BASH_REMATCH[1]}"
fi

epic="${BCT_RELEASE_EPIC:-}"
if [[ -z "$epic" ]]; then
  if [[ -n "$default_epic" ]]; then
    read -r -p "Epic summary (default: \"$default_epic\"): " epic
    epic="${epic:-$default_epic}"
  else
    read -r -p "Epic summary (will become \"v${ver} — Epic: <text>\"): " epic
  fi
fi
epic="$(printf '%s' "$epic" | sed -E 's/^[[:space:]]+//; s/[[:space:]]+$//')"
[[ -n "$epic" ]] || die "Epic summary is required"

commit_msg="v${ver} — Epic: ${epic}"

# Ensure changelog exists (interactive only if missing)
"$ENSURE_CHANGELOG"

[[ -f "$CHANGELOG_PATH" ]] || die "Changelog missing after ensure script: $CHANGELOG_PATH"
chg_len="$(wc -c < "$CHANGELOG_PATH" | tr -d ' ')"
(( chg_len <= 500 )) || die "F-Droid changelog too long (${chg_len} chars, max 500): $CHANGELOG_PATH"

# Update fdroid-template.yml to match current VERSION + versionCode
# Policy: commit tag for the mirror repo uses "-fdroid" suffix.
python3 - <<PY
import pathlib, re, sys

path = pathlib.Path("${FROID_TEMPLATE}")
s = path.read_text(encoding="utf-8")
lines = s.splitlines(True)

ver = "${ver}"
vc = "${VC}"
commit = f"v{ver}-fdroid"

repl_counts = {
  "CurrentVersion": 0,
  "CurrentVersionCode": 0,
  "Builds.versionName": 0,
  "Builds.versionCode": 0,
  "Builds.commit": 0,
}

in_builds = False
first_build_active = False
seen_first_build = False

out = []

for line in lines:
  # Top-level fields
  if re.match(r'^CurrentVersion:\s*', line):
    out.append(f"CurrentVersion: {ver}\n")
    repl_counts["CurrentVersion"] += 1
    continue

  if re.match(r'^CurrentVersionCode:\s*', line):
    out.append(f"CurrentVersionCode: {vc}\n")
    repl_counts["CurrentVersionCode"] += 1
    continue

  # Track Builds block
  if re.match(r'^Builds:\s*$', line):
    in_builds = True
    out.append(line)
    continue

  # Detect build item starts inside Builds:
  if in_builds and re.match(r'^\s*-\s*', line):
    if not seen_first_build:
      seen_first_build = True
      first_build_active = True
    else:
      first_build_active = False

  # If we leave Builds block (a new top-level key), stop tracking
  if in_builds and re.match(r'^[A-Za-z][A-Za-z0-9_]*:\s*', line):
    in_builds = False
    first_build_active = False

  # Update the first build entry fields only
  if first_build_active:
    m = re.match(r'^(\s*)-\s*versionName:\s*.*$', line)
    if m:
      indent = m.group(1)
      out.append(f"{indent}- versionName: {ver}\n")
      repl_counts["Builds.versionName"] += 1
      continue

    m = re.match(r'^(\s*)versionName:\s*.*$', line)
    if m:
      indent = m.group(1)
      out.append(f"{indent}versionName: {ver}\n")
      repl_counts["Builds.versionName"] += 1
      continue

    m = re.match(r'^(\s*)versionCode:\s*.*$', line)
    if m:
      indent = m.group(1)
      out.append(f"{indent}versionCode: {vc}\n")
      repl_counts["Builds.versionCode"] += 1
      continue

    m = re.match(r'^(\s*)commit:\s*.*$', line)
    if m:
      indent = m.group(1)
      out.append(f"{indent}commit: {commit}\n")
      repl_counts["Builds.commit"] += 1
      continue

  out.append(line)

missing = [k for k,v in repl_counts.items() if v == 0]
if missing:
  sys.stderr.write("ERROR: fdroid-template.yml is missing required fields:\n")
  for k in missing:
    sys.stderr.write(f"  - {k}\n")
  sys.stderr.write("\nExpected at minimum:\n")
  sys.stderr.write("  Builds:\\n    - versionName: X.Y.Z\\n      versionCode: 123\\n      commit: vX.Y.Z-fdroid\\n")
  sys.stderr.write("  CurrentVersion: X.Y.Z\\n  CurrentVersionCode: 123\\n")
  sys.exit(1)

path.write_text("".join(out), encoding="utf-8")
PY

# Stage everything, show summary, confirm
git add -A
 

echo
echo "== Staged changes =="
git status --porcelain || true
echo
git diff --cached --stat || true
echo

confirm="${BCT_RELEASE_CONFIRM:-}"
if [[ -z "$confirm" ]]; then
  read -r -p "Commit and push as: \"$commit_msg\" ? [y/N] " confirm
fi
case "${confirm,,}" in
  y|yes) ;;
  *) die "Aborted by user (no commit performed)." ;;
esac

if git diff --cached --quiet; then
  git commit --allow-empty -m "$commit_msg"
else
  git commit -m "$commit_msg"
fi

git push origin HEAD

info "OK: release commit prepared and pushed."
