#!/usr/bin/env bash
# scripts/synchronise-fdroid.sh
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC_REPO="$ROOT_DIR"

# Expected workspace layout:
# <workspace>/beemage
# <workspace>/beemage-fdroid
DEFAULT_DST_REPO="$(cd "$ROOT_DIR/.." && pwd)/beemage-fdroid"
DST_REPO="${1:-$DEFAULT_DST_REPO}"

die() { echo "ERROR: $*" >&2; exit 1; }
need() { command -v "$1" >/dev/null 2>&1 || die "Missing command: $1"; }

need rsync
need git

[[ -d "$DST_REPO" ]] || die "Destination repo not found: $DST_REPO"
[[ -d "$DST_REPO/.git" ]] || die "Destination is not a git repo: $DST_REPO"

echo "=== synchronise-fdroid ==="
echo "From: $SRC_REPO"
echo "To:   $DST_REPO"
echo

# Safety: refuse if destination has uncommitted changes
if [[ -n "$(git -C "$DST_REPO" status --porcelain)" ]]; then
  die "Destination repo has uncommitted changes. Commit/stash them first: $DST_REPO"
fi

# Define what to mirror
INCLUDE_PATHS=(
  "VERSION"
  "src/"
  "apps/android-web/"
  "apps/android-native/"
)

# Define exclusions inside included paths (generated outputs, etc.)
RSYNC_EXCLUDES=(
  "--exclude=node_modules/"
  "--exclude=dist/"
  "--exclude=.cache/"
  "--exclude=.vite/"
  "--exclude=.turbo/"
  "--exclude=.next/"
  "--exclude=coverage/"
  "--exclude=*.log"
  "--exclude=.DS_Store"
  "--exclude=.idea/"
  "--exclude=*.iml"
  "--exclude=.gradle/"
  "--exclude=**/build/"
  "--exclude=local.properties"
  "--exclude=release/"
  "--exclude=keystore.properties"
  "--exclude=*.jks"
  "--exclude=*.keystore"
  # assets are generated by android-web build step
  "--exclude=app/src/main/assets/**"
  # never mirror local testing file
  "--exclude=.fdroid.yml"
)

echo "== Cleaning destination mirrored paths =="
for p in "${INCLUDE_PATHS[@]}"; do
  rm_target="${p%/}"
  if [[ -e "$DST_REPO/$rm_target" ]]; then
    echo " - rm -rf $DST_REPO/$rm_target"
    rm -rf "$DST_REPO/$rm_target"
  fi
done

# Ensure destination skeleton exists
mkdir -p "$DST_REPO/src" "$DST_REPO/apps"

echo
echo "== Mirroring selected paths =="
for p in "${INCLUDE_PATHS[@]}"; do
  src="$SRC_REPO/$p"
  [[ -e "$src" ]] || die "Missing source path: $src"

  mkdir -p "$(dirname "$DST_REPO/$p")"

  echo " - $p"
  rsync -a --delete \
    "${RSYNC_EXCLUDES[@]}" \
    "$src" "$DST_REPO/$p"
done

echo
echo "== Post-sync info =="
echo "Destination status:"
git -C "$DST_REPO" status --porcelain || true
echo

cat <<'NEXT'
Next steps (in beemage-fdroid):
  cd ../beemage-fdroid
  git add -A
  git commit -m "sync: update mirror from beemage"
  git push

Local fdroidserver test (optional):
  cd ../beemage-fdroid
  cp -f fdroid-template.yml .fdroid.yml
  fdroid readmeta
  fdroid build

Tagging for F-Droid (example):
  git tag -a v0.2.5-fdroid -m "BeeMage 0.2.5 (fdroid mirror)"
  git push origin v0.2.5-fdroid
NEXT